# Generated by Django 4.1.2 on 2022-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('alink', models.CharField(max_length=500)),
                ('flink', models.CharField(max_length=500)),
            ],
        ),
    ]
