# Generated by Django 4.1.2 on 2022-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_time_history_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
